[application]
port = 8083  # Default port for `dx serve`

[web.app]

# HTML title tag content
title = "rental_calculator"

# include `assets` in web platform
[web.resource]
# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
identifier = "com.rayburncode"
publisher = "RayburnCode"
icon = ["assets/icon.icns"]
resources = ["assets/tailwind.css", "assets/header.svg"]
