[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
dioxus = "0.6.3"
dioxus-desktop = "0.6.3"
dioxus-signals = "0.6.3"
dioxus-router = "0.6.3"
chrono = "0.4.41"

[features]
default = []
server = []
